const FLASHCARD_DECKS = [{
  title: 'Korean Alphabet',
  words: {
    'ㄱ': 'giyeok',
    'ㄴ': 'nieun',
    'ㄷ': 'digeut',
    'ㄹ': 'rieul',
    'ㅁ': 'mieum',
    'ㅂ': 'bieup',
    'ㅅ': 'siot',
    'ㅇ': 'ieung',
    'ㅈ': 'jieut',
    'ㅊ': 'chieut',
    'ㅋ': 'kieuk',
    'ㅌ': 'tieut',
    'ㅍ': 'pieup',
    'ㅎ': 'hieut',
    'ㄲ': 'ssanggiyeok',
    'ㄸ': 'ssangdigeut',
    'ㅃ': 'ssangbieup',
    'ㅆ': 'ssangsiot',
    'ㅉ': 'ssangjieut',
    'ㅏ': 'a',
    'ㅑ': 'ya',
    'ㅓ': 'eo',
    'ㅕ': 'yeo',
    'ㅗ': 'o',
    'ㅛ': 'yo',
    'ㅜ': 'u',
    'ㅠ': 'yu',
    'ㅡ': 'eu',
    'ㅣ': 'i',
    'ㅐ': 'ae',
    'ㅒ': 'yae',
    'ㅔ': 'e',
    'ㅖ': 'ye',
    'ㅘ': 'wa',
    'ㅙ': 'wae',
    'ㅚ': 'oe',
    'ㅝ': 'wo',
    'ㅞ': 'we',
    'ㅟ': 'wi',
    'ㅢ': 'ui'
  }
}, {
  title: 'Korean Verbs',
  words: {
    '가다': 'to go',
    'conjugate 가다': '가요',
    '자다': 'to sleep',
    'conjugate 자다': '자요',
    '오다': 'to come',
    'conjugate 오다': '와요',
    '보다': 'to see/watch',
    'conjugate 보다': '봐요',
    '먹다': 'to eat',
    'conjugate 먹다': '먹어요',
    '마시다': 'to drink',
    'conjugate 마시다': '마셔요',
    '공부하다': 'to study',
    'conjugate 공부하다': '공부해요',
    '운동하다': 'to do exercise',
    'conjugate 운동하다': '운동해요',
    '전화하다': 'to call',
    'conjugate 전화하다': '전화해요',
    '일하다': 'to work',
    'conjugate 일하다': '일해요',
    '이야기하다': 'to talk',
    'conjugate 이야기하다': '이야기해요',
    '쇼핑하다': 'to shop',
    'conjugate 쇼핑하다': '쇼핑해요',
  }
}, {
  title: 'Basic Korean Words',
  words: {
    '여자': 'woman',
    '남자': 'man',
    '사람': 'person',
    '나무': 'tree',
    '호수': 'lake',
    '구름': 'cloud',
    '땅': 'ground'
  }
}, {
  title: 'Foods in Korean',
  words: {
    '사과': 'apple',
    '빵': 'bread',
    '치즈': 'cheese',
    '우유': 'milk',
    '커피': 'coffee',
    '바나나': 'banana',
    '복숭아': 'peach'
  }
}];
